# AuthServer config file
# Use '&' for colors
# Placeholders for join message:
#  %player% - Replaced with the player's name

join_message: '&aWelcome %player%!'
tablist.header: 'Header'
tablist.footer: 'Footer'
scoreboard.title: 'AuthServer'

scoreboard.lines:
  - 'Login with /login'
  - 'Register with /register'