# AuthServer config file
# Use '&' for colors
# Placeholders for join message:
#  %player% - Replaced with the player's name

join_message:
  enabled: false
  message:
    - '&aWelcome %player%!'
    - 'Login with /login'
  # Global message. Leave this empty to disable
  global: ''

on_join_teleport:
  enabled: false

  # if empty x:0 y:0 z:0 yaw:0 pitch:0
  x:
  y:
  z:
  yaw:
  pitch:

# Global message. Leave this empty to disable
leave_message:
  global: '%player% just left, we''ll miss them.'

tablist:
  enabled: false
  header: 'Header'
  footer: 'Footer'

scoreboard:
  enabled: false
  title: 'AuthServer'
  lines:
    - 'Login with /login'
    - 'Register with /register'

# Allow players not in Creative mode to chat
enable_chat: false

# Allow players not in Creative mode to move
enable_movement: false

# Allow players to receive damage
enable_damage: false